www/ploa00/cv01/css/style.css
www/ploa00/cv01/index.php

Dobrý večer, odevzdávám dú z prvního cvičení
https://eso.vse.cz/~ploa00/cv01/

ploa00-cv01

---

www/podj06/cv01/css/main.css
www/podj06/cv01/index.php

ESO: https://eso.vse.cz/~podj06/cv01/

podj06-cv01

---

www/mikm25/cv1/css/style.css
www/mikm25/cv1/index.php

Dobrý den, odevzdávám cvičení 1.
odkaz na serveru je: https://eso.vse.cz/~mikm25/cv1/

mikm25-cv01

---

www/vevj00/cv1/index.php
www/vevj00/cv1/main.css

Odevzdávám cv 01
odkaz je na https://eso.vse.cz/~vevj00/cv1/

vevj00-cv01

---

www/cv01/css/main.css
www/cv01/index.php
www/urvo00/cv01/css/main.css
www/urvo00/cv01/index.php

Odevzdávám cv01, odkaz na server eso: [https://eso.vse.cz/~urvo00/cv01/](https://eso.vse.cz/~urvo00/cv01/)

urvo00-cv01

---

www/urvo00/cv02/css/main.css
www/urvo00/cv02/index.php

Dobrý den, odevzdávám cv02.
Odkaz na server eso: [https://eso.vse.cz/~urvo00/cv02/](https://eso.vse.cz/~urvo00/cv02/)

urvo00-cv02

---

www/podj06/cv02/css/main.css
www/podj06/cv02/index.php

https://eso.vse.cz/~podj06/cv02/

podj06-cv02

---

www/mikt04/cv02/index.php
www/mikt04/cv02/main.css

https://eso.vse.cz/~mikt04/webove-aplikace/cv02/index.php

mikt04-cv02

---

www/ploa00/cv02/css/style.css
www/ploa00/cv02/index.php

Dobrý večer, odevzdávám dú č. 2
https://eso.vse.cz/~ploa00/cv02/

ploa00-cv02

---

www/mikt04/cv03/css/main.css
www/mikt04/cv03/includes/foot.php
www/mikt04/cv03/includes/head.php
www/mikt04/cv03/index.php
www/mikt04/cv03/registration-success.php

https://eso.vse.cz/~mikt04/webove-aplikace/cv03/index.php

mikt04-cv03

---

www/mikm25/cv3/index.php
www/mikm25/cv3/models/EmailSender.php
www/mikm25/cv3/models/SignupForm.php
www/mikm25/cv3/views/form.php
www/mikm25/cv3/views/template/footer.php
www/mikm25/cv3/views/template/header.php

https://eso.vse.cz/~mikm25/cv3/

mikm25-cv3

---

www/vevj00/cv3/includes/header.php
www/vevj00/cv3/index.php
www/vevj00/cv3/registration-success.php

odevzdavam cv 03
dostupné na adrese https://eso.vse.cz/~vevj00/cv03/

veve97-cv03

---

www/otoj00/cv3/index.php
www/otoj00/cv3/utils/validation.php
www/otoj00/cv4/login.php
www/otoj00/cv4/registration.php
www/otoj00/cv4/utils/User.php
www/otoj00/cv4/utils/access.php
www/otoj00/cv4/utils/validation.php

Dobrý den,
odevzdávám můj úkol na cv4.
Odkaz na eso server: [link](https://eso.vse.cz/~otoj00/cv4/registration.php)

otoj00-cv4

---

www/otoj00/cv3/index.php
www/otoj00/cv3/utils/validation.php
www/otoj00/cv4/login.php
www/otoj00/cv4/registration.php
www/otoj00/cv4/utils/User.php
www/otoj00/cv4/utils/access.php
www/otoj00/cv4/utils/validation.php

Dobrý den,
odevzdávám zpětně úkol 3.
Mohl bych vás poprosit o dodatečnou kontrolu úkolu č.3 ?
Odkaz na server eso [link](https://eso.vse.cz/~otoj00/cv3/index.php)
Děkuji s přáním příjemného dne,
Jiří

otoj00-cv3

---

www/mikm25/cv4/dashboard.php
www/mikm25/cv4/db/UserDatabase.php
www/mikm25/cv4/db/data/users.db.csv
www/mikm25/cv4/db/models/User.php
www/mikm25/cv4/index.php
www/mikm25/cv4/login.php
www/mikm25/cv4/models/PasswordBroker.php
www/mikm25/cv4/models/forms/Form.php
www/mikm25/cv4/models/forms/LoginForm.php
www/mikm25/cv4/models/forms/RegistrationForm.php
www/mikm25/cv4/registration.php
www/mikm25/cv4/views/dashboard.php
www/mikm25/cv4/views/home.php
www/mikm25/cv4/views/login/form.php
www/mikm25/cv4/views/registration/form.php
www/mikm25/cv4/views/template/footer.php
www/mikm25/cv4/views/template/header.php

https://eso.vse.cz/~mikm25/cv4/

mikm25-cv4

---

www/mikt04/cv04/css/main.css
www/mikt04/cv04/dashboard.php
www/mikt04/cv04/includes/foot.php
www/mikt04/cv04/includes/head.php
www/mikt04/cv04/index.php
www/mikt04/cv04/login.php
www/mikt04/cv04/registration-success.php
www/mikt04/cv04/users.db
www/mikt04/cv04/users.php
www/mikt04/cv04/utils.php

https://eso.vse.cz/~mikt04/webove-aplikace/cv04/index.php

mikt04-cv04

---

www/zavm07/cv02/index.php
www/zavm07/cv03/dashboard.php
www/zavm07/cv03/index.php
www/zavm07/cv03/login.php
www/zavm07/cv03/users.db
www/zavm07/cv03/users.php
www/zavm07/cv03/utils.php
www/zavm07/cv05/Database.php
www/zavm07/cv05/DatabaseOperations.php
www/zavm07/cv05/config.php
www/zavm07/cv05/db.php

Odevzdávám úkol z cv05
https://eso.vse.cz/~zavm07/cv05/

zavm07-cv05

---

www/otoj00/cv5/db_config.php
www/otoj00/cv5/index.php
www/otoj00/cv5/objects/DB.php
www/otoj00/cv5/objects/IDatabaseOperations.php
www/otoj00/cv5/objects/OrdersDB.php
www/otoj00/cv5/objects/ProductsDB.php
www/otoj00/cv5/objects/UsersDB.php

Dobrý den,
odevzdávám úkol č.5, náhled na stránce:
[odkaz](https://eso.vse.cz/~otoj00/cv5/index.php)

otoj00-cv05

---

www/staj19/cv05/books.php
www/staj19/cv05/classes/BooksDB.php
www/staj19/cv05/classes/DB.php
www/staj19/cv05/classes/DatabaseOperations.php
www/staj19/cv05/classes/OrdersDB.php
www/staj19/cv05/classes/UsersDB.php
www/staj19/cv05/index.html
www/staj19/cv05/orders.php
www/staj19/cv05/users.php

Odevzdavam cviceni 05
odkaz na prace na serveru eso je https://eso.vse.cz/~staj19/cv05/

staj19-cv05

---

www/mikt04/cv01/index.php
www/mikt04/cv05/BooksDB.php
www/mikt04/cv05/Database.php
www/mikt04/cv05/DatabaseOperations.php
www/mikt04/cv05/OrdersDB.php
www/mikt04/cv05/ProductsDB.php
www/mikt04/cv05/UsersDB.php
www/mikt04/cv05/config.php
www/mikt04/cv05/index.php
www/mikt04/cv05/orders.php
www/mikt04/cv05/products.php
www/mikt04/cv05/users.php

https://eso.vse.cz/~mikt04/webove-aplikace/cv05/index.php

mikt04-cv05

---

www/dusj08/cv05/config.php
www/dusj08/cv05/database.php
www/dusj08/cv05/databaseOperations.php
www/dusj08/cv05/index.php
www/dusj08/cv05/orders.php
www/dusj08/cv05/ordersDB.php
www/dusj08/cv05/products.php
www/dusj08/cv05/productsDB.php
www/dusj08/cv05/users.php
www/dusj08/cv05/usersDB.php

Odevzdaná prace ze cvičení č. 5.
Dostupné na: https://eso.vse.cz/~dusj08/du05/

dusj08-cv05

---

www/hejd02/cv05/config/config.php
www/hejd02/cv05/index.php
www/hejd02/cv05/interfaces/DatabaseOperations.php
www/hejd02/cv05/models/DB.php
www/hejd02/cv05/models/OrdersDB.php
www/hejd02/cv05/models/ProductsDB.php
www/hejd02/cv05/models/UsersDB.php

hejd02-cv05

---

www/jurt03/cv05/Database.php
www/jurt03/cv05/DatabaseOperations.php
www/jurt03/cv05/OrdersDB.php
www/jurt03/cv05/ProductsDB.php
www/jurt03/cv05/UsersDB.php
www/jurt03/cv05/index.php
www/jurt03/cv05/orders.php
www/jurt03/cv05/products.php
www/jurt03/cv05/users.php

Dobry den,
odevzdavam cviceni 05.
Odkaz na práce na serveru eso je https://eso.vse.cz/~jurt03/cv05/

jurt03-cv05

---

www/jurt03/cv06/components/CategoryDisplay.php
www/jurt03/cv06/components/ProductDisplay.php
www/jurt03/cv06/components/SlideDisplay.php
www/jurt03/cv06/css/styles.css
www/jurt03/cv06/db/CategoriesDB.php
www/jurt03/cv06/db/Database.php
www/jurt03/cv06/db/DatabaseOperations.php
www/jurt03/cv06/db/ProductsDB.php
www/jurt03/cv06/db/SlidesDB.php
www/jurt03/cv06/db/config.php
www/jurt03/cv06/includes/footer.php
www/jurt03/cv06/includes/header.php
www/jurt03/cv06/index.php

Odevzdavam cviceni 06
odkaz na práce na serveru eso je https://eso.vse.cz/~jurt03/cv06/

jurt03-cv06

---

www/staj19/cv07/buy.php
www/staj19/cv07/cart.php
www/staj19/cv07/classes/DB.php
www/staj19/cv07/classes/DatabaseOperations.php
www/staj19/cv07/classes/ProductsDB.php
www/staj19/cv07/cred.php
www/staj19/cv07/foot.php
www/staj19/cv07/head.php
www/staj19/cv07/index.php
www/staj19/cv07/login.php
www/staj19/cv07/logout.php
www/staj19/cv07/nav.php
www/staj19/cv07/products.php
www/staj19/cv07/profile.php
www/staj19/cv07/removeItem.php
www/staj19/cv07/styles/style.css

Odevzdavam cviceni 07
Odkaz na praci na server eso je https://eso.vse.cz/~staj19/cv07/

staj19-cv07

---

www/urvo00/cv07/buy.php
www/urvo00/cv07/cart.php
www/urvo00/cv07/config.php
www/urvo00/cv07/create-item.php
www/urvo00/cv07/db.php
www/urvo00/cv07/delete-item.php
www/urvo00/cv07/edit-item.php
www/urvo00/cv07/incl/footer.php
www/urvo00/cv07/incl/header.php
www/urvo00/cv07/incl/navbar.php
www/urvo00/cv07/index.php
www/urvo00/cv07/login.php
www/urvo00/cv07/logout.php
www/urvo00/cv07/profile.php
www/urvo00/cv07/remove-item.php
www/urvo00/cv07/styles.css

Dobrý den, odevzdávám úkol z cv07,
odkaz na server eso: [https://eso.vse.cz/~urvo00/cv07](https://eso.vse.cz/~urvo00/cv07)

urvo00-cv07

---

www/zemt08/cv07/buy.php
www/zemt08/cv07/cart.php
www/zemt08/cv07/config.php
www/zemt08/cv07/create-item.php
www/zemt08/cv07/db.php
www/zemt08/cv07/delete-item.php
www/zemt08/cv07/edit-item.php
www/zemt08/cv07/incl/footer.php
www/zemt08/cv07/incl/header.php
www/zemt08/cv07/incl/navbar.php
www/zemt08/cv07/index.php
www/zemt08/cv07/login.php
www/zemt08/cv07/logout.php
www/zemt08/cv07/profile.php
www/zemt08/cv07/remove-item.php
www/zemt08/cv07/styles.css

Cvičení 07
eso: https://eso.vse.cz/~zemt08/cv07/

zemt08-cv07

---

www/staj19/cv08/adminRequired.php
www/staj19/cv08/buy.php
www/staj19/cv08/cart.php
www/staj19/cv08/classes/DB.php
www/staj19/cv08/classes/DatabaseOperations.php
www/staj19/cv08/classes/ProductsDB.php
www/staj19/cv08/classes/UsersDB.php
www/staj19/cv08/cred.php
www/staj19/cv08/delete.php
www/staj19/cv08/edit.php
www/staj19/cv08/foot.php
www/staj19/cv08/head.php
www/staj19/cv08/index.php
www/staj19/cv08/login.php
www/staj19/cv08/logout.php
www/staj19/cv08/managerRequired.php
www/staj19/cv08/nav.php
www/staj19/cv08/new.php
www/staj19/cv08/products.php
www/staj19/cv08/profile.php
www/staj19/cv08/register.php
www/staj19/cv08/removeItem.php
www/staj19/cv08/styles/style.css
www/staj19/cv08/userRequired.php
www/staj19/cv08/users.php
www/staj19/cv08/worldClock.php

Odevzdavam cviceni 08
Odkaz na praci na serveru eso je https://eso.vse.cz/~staj19/cv08/index.php

staj19-cv08

---

www/urvo00/cv08/buy.php
www/urvo00/cv08/cart.php
www/urvo00/cv08/config.php
www/urvo00/cv08/create-item.php
www/urvo00/cv08/db.php
www/urvo00/cv08/delete-item.php
www/urvo00/cv08/edit-item.php
www/urvo00/cv08/incl/footer.php
www/urvo00/cv08/incl/header.php
www/urvo00/cv08/incl/navbar.php
www/urvo00/cv08/index.php
www/urvo00/cv08/login.php
www/urvo00/cv08/logout.php
www/urvo00/cv08/profile.php
www/urvo00/cv08/remove-item.php
www/urvo00/cv08/requireAdmin.php
www/urvo00/cv08/requireManager.php
www/urvo00/cv08/signup.php
www/urvo00/cv08/styles.css
www/urvo00/cv08/users.php
www/urvo00/cv08/world-clock.php

Dobrý den, odevzdávám úkol z cv08,
odkaz na server eso: [https://eso.vse.cz/~urvo00/cv08](https://eso.vse.cz/~urvo00/cv08)

urvo00-cv08

---

www/zemt08/cv08/buy.php
www/zemt08/cv08/cart.php
www/zemt08/cv08/check-access.php
www/zemt08/cv08/check-user.php
www/zemt08/cv08/config.php
www/zemt08/cv08/create-item.php
www/zemt08/cv08/db.php
www/zemt08/cv08/delete-item.php
www/zemt08/cv08/edit-item.php
www/zemt08/cv08/incl/footer.php
www/zemt08/cv08/incl/header.php
www/zemt08/cv08/incl/navbar.php
www/zemt08/cv08/index.php
www/zemt08/cv08/login.php
www/zemt08/cv08/logout.php
www/zemt08/cv08/profile.php
www/zemt08/cv08/remove-item.php
www/zemt08/cv08/signup.php
www/zemt08/cv08/styles.css
www/zemt08/cv08/users.php
www/zemt08/cv08/world-clock.php

Cvičení 08
dostupné na: https://eso.vse.cz/~zemt08/cv08/index.php

zemt08-cv08

---

www/staj19/cv09/db.php
www/staj19/cv09/edit.php
www/staj19/cv09/editPess.php
www/staj19/cv09/foot.php
www/staj19/cv09/head.php
www/staj19/cv09/index.php
www/staj19/cv09/register.php

Odevzdavam cviceni 09
Odkaz na praci na server eso je https://eso.vse.cz/~staj19/cv09/

staj19-cv09
